In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import make_regression

In [3]:
X, y = make_regression(n_samples=1000, n_features=2, noise = 10)


In [5]:
X

array([[-1.10095158,  0.44733075],
       [ 0.82642825,  1.79810271],
       [ 0.0026066 ,  0.77101043],
       ...,
       [-0.43314605,  0.07677621],
       [ 0.12796943,  0.40955634],
       [-1.80351873, -0.73761333]])

In [6]:
y

array([-3.77597266e+00,  4.39970412e+00,  1.59068584e+01,  1.33153729e+01,
       -1.16459723e+00, -2.07194980e+01,  5.67939988e+00,  1.32060704e+01,
       -1.76272616e+01, -9.23974904e-01, -3.29533202e+00,  3.54361188e+01,
        3.64692220e+01, -1.63567437e+01,  6.06840819e+00, -1.23173938e+01,
       -1.37974408e+01,  7.95003721e+00,  1.85585248e+01, -2.37495647e+01,
        4.83396333e+00, -2.10090283e+01, -1.48719394e+01, -1.12054028e+01,
        1.78764997e+01, -1.60014563e+01, -1.87716122e+01,  3.70450860e+01,
        7.21755016e+00, -4.19069649e+00, -6.62095483e+00, -1.60676219e+01,
       -2.28725609e+01,  9.56471261e+00, -1.62568087e+01,  8.50880844e+00,
        3.45377564e+01,  3.01409764e+01, -1.36229191e+01, -2.73286255e+01,
        2.84380293e+01, -1.36474368e+01, -1.70707483e-01,  1.95210331e+01,
        2.19278675e+01, -8.91492434e+00, -1.10192230e+01, -7.23805383e+00,
       -1.71129581e+00, -4.68561767e+00, -2.61467273e+01,  1.42687087e+01,
        2.49952987e+00,  

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.25, random_state = 50)

In [8]:
from sklearn.neighbors import KNeighborsRegressor
knr_model = KNeighborsRegressor(n_neighbors=5)

In [9]:
knr_model = knr_model.fit(X_train, y_train)

In [10]:
knr_model

KNeighborsRegressor()

In [13]:
y_pred = knr_model.predict(X_test)
y_pred

array([ 9.61010199e+00,  7.18019628e+00, -2.17890540e+01,  1.22852315e+01,
        1.16987692e+01,  1.78563931e+01, -6.01808392e+00,  2.79285130e+00,
       -6.47361224e+00,  1.11231361e+01,  3.34463534e+01, -1.29009190e+01,
       -4.07235842e+00, -6.99585468e+00, -1.66688961e+01,  5.73299370e+00,
        1.12101180e+01, -2.02393725e+01,  6.85735806e-01,  1.44930902e+01,
        1.82340412e+01, -1.12616846e+01,  5.90160453e+00, -8.35199723e+00,
        4.68596473e-01, -1.07380584e+01, -1.65141231e+00, -1.23411895e+01,
        9.45216467e+00, -3.13980065e-01, -8.01186154e+00, -1.20750779e+01,
        4.53158908e+00, -2.08202784e+01, -1.42515454e+01, -1.20060911e+01,
       -3.29915192e+00,  2.00813359e+01, -1.58259007e+01,  9.56661364e-01,
        9.56145773e+00, -2.43797443e+00, -9.08397860e+00, -7.58948723e+00,
       -7.64294516e+00,  4.51067712e+00, -1.82053313e-01, -6.45869535e+00,
        2.15308356e+01, -2.27254896e+00, -1.06435269e+01,  9.04237700e+00,
       -2.05404910e+01,  

In [14]:
from sklearn.metrics import r2_score

print(r2_score(y_test, y_pred))

0.52535219606726


In [15]:
from sklearn.model_selection import GridSearchCV

In [23]:
params = {
    'n_neighbors' : [3,4,5],
    'weights' : ['uniform', 'distance'],
    'algorithm': ['ball_tree', 'kd_tree', 'brute'],
    'p' : [1,2]

}

#  When p = 1, this is equivalent to using manhattan_distance (l1), and euclidean_distance (l2) for p = 2

In [24]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()

In [26]:
gscv = GridSearchCV(estimator = knr_model, param_grid = params, cv=5, scoring = 'r2')

In [27]:
gscv_model  = gscv.fit(X_train, y_train)
gscv_model

c:\Users\saike\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\saike\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\saike\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 234, in __call__
    return self._score(
           ^^^^^^^^^^^^
  File "c:\Users\saike\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 276, in _score
    y_pred = method_caller(estimator, "predict", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\saike\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 4, 5], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='r2')

In [28]:
y_pred_res = gscv_model.predict(X_test)

In [29]:
y_pred_res

array([ 6.01252388e+00,  6.85374129e-01, -2.53885390e+01,  1.22852315e+01,
        1.16987692e+01,  2.21850220e+01, -6.01808392e+00,  4.89449340e+00,
       -6.47361224e+00,  1.11231361e+01,  3.50953246e+01, -1.52568635e+01,
       -4.07235842e+00, -6.99585468e+00, -1.71201137e+01,  3.58761523e+00,
        1.40458679e+01, -2.02393725e+01,  6.85735806e-01,  1.48524324e+01,
        1.82340412e+01, -1.12616846e+01,  5.90160453e+00, -8.35199723e+00,
        4.68596473e-01, -1.23075124e+01, -1.65141231e+00, -1.23411895e+01,
        7.42405843e+00, -5.83815981e-01, -5.23359507e+00, -1.20750779e+01,
        4.53158908e+00, -2.08202784e+01, -1.42515454e+01, -1.14231868e+01,
       -6.99585468e+00,  2.00813359e+01, -1.58259007e+01,  9.56661364e-01,
        9.56145773e+00, -2.43797443e+00, -1.00984136e+01, -7.58948723e+00,
       -8.69153196e+00,  2.47557138e-01, -1.82053313e-01, -6.45869535e+00,
        2.04650861e+01, -1.79360579e+00, -1.06435269e+01,  9.68648024e+00,
       -1.93218243e+01,  

In [30]:
from sklearn.metrics import r2_score

print(r2_score(y_test, y_pred_res))

0.5315856014593352


In [31]:
gscv_model.best_params_

{'algorithm': 'ball_tree', 'n_neighbors': 5, 'p': 1, 'weights': 'uniform'}

In [32]:
gscv_model.best_score_

0.6271659426913255