In [1]:
pwd

'C:\\Users\\saike'

In [4]:
import os
os.getcwd()
os.chdir("C:\\Users\\saike\\OneDrive\\Desktop\\Series\\ML\\Logistic Regression")

In [5]:
pwd

'C:\\Users\\saike\\OneDrive\\Desktop\\Series\\ML\\Logistic Regression'

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
from sklearn.datasets import make_classification

In [10]:
X, y = make_classification(n_samples=100, n_features=10, n_classes=2)

In [11]:
X.shape

(100, 10)

In [12]:
y.shape

(100,)

In [13]:
X

array([[ 1.48413914e-01,  5.07523191e-01, -6.03002801e-01,
        -1.47280133e-01,  3.30489950e-01,  9.46888145e-01,
         2.54781790e-01,  8.21213132e-02, -8.62064608e-01,
         1.53931641e-01],
       [ 2.39398545e-01,  1.99391760e-01, -2.81603760e-01,
        -3.34693157e-01,  6.66989808e-01, -6.87303529e-01,
         9.50815076e-02,  4.30926610e-01, -2.07516009e-01,
        -5.35822352e-02],
       [ 4.38790587e-02, -4.76027309e-01, -1.13726443e+00,
        -2.03943718e-01, -1.45244273e-02, -2.99526534e-02,
        -2.13646027e+00,  4.58879714e-02,  3.03987191e-01,
         3.25149933e-01],
       [-3.69404960e-01, -2.11534827e-01, -1.89889424e+00,
        -3.25365897e-01, -2.04629041e+00, -5.87082234e-01,
        -8.11100706e-01,  5.42386815e-02, -1.80815950e+00,
         5.50056865e-01],
       [ 1.76630111e-01, -1.44128675e+00, -1.05265218e+00,
         1.01610620e+00,  1.15326616e+00, -3.44252680e-01,
         1.39018361e+00, -1.73632351e+00,  1.55671931e-01,
         8.

In [14]:
y

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0])

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 68)

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
lr = LogisticRegression()
lr

LogisticRegression()

In [31]:
model = lr.fit(X_train, y_train)

In [32]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [33]:
y_test, y_pred

(array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0]))

In [34]:
# Preformance metrics

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

1.0
[[12  0]
 [ 0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



# Hyperparameter Tuning in Logistic Regression

## GridSearch CV

#### Hyperparameters: Parameters not learned by the model from the data but set by the user.
#### Cross-validation (CV): A technique to split the dataset into training and testing subsets multiple times to evaluate the model's performance consistently

In [35]:
from sklearn.model_selection import GridSearchCV

In [37]:
model = LogisticRegression()

In [45]:
params = {
    'penalty' : ['l1', 'l2', 'elasticnet'],
    'C' : [1.0,10.0,100.0],
    'solver' : ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
}

In [46]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [1.0, 10.0, 100.0],
 'solver': ['lbfgs',
  'liblinear',
  'newton-cg',
  'newton-cholesky',
  'sag',
  'saga']}

In [42]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()

In [47]:
gcv = GridSearchCV(estimator = model , param_grid= params, cv = 5, scoring = 'accuracy')

In [48]:
gcv

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1.0, 10.0, 100.0],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [49]:
model1 = gcv.fit(X_train, y_train)

C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter 

In [50]:
model1

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1.0, 10.0, 100.0],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [51]:
y_preds = model1.predict(X_test)

In [53]:
y_test, y_preds

(array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0]))

In [54]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test,y_preds))

print(confusion_matrix(y_test,y_preds))

print(classification_report(y_test,y_preds))

1.0
[[12  0]
 [ 0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [55]:
model1.best_params_

{'C': 10.0, 'penalty': 'l2', 'solver': 'lbfgs'}

In [56]:
model1.best_score_

0.9125

In [57]:
model1.predict_proba(X_test)

array([[9.14114401e-01, 8.58855991e-02],
       [9.99907694e-01, 9.23064427e-05],
       [8.06191400e-01, 1.93808600e-01],
       [2.79231757e-01, 7.20768243e-01],
       [2.74548943e-02, 9.72545106e-01],
       [9.99023494e-01, 9.76505905e-04],
       [9.92074428e-01, 7.92557224e-03],
       [9.94867936e-01, 5.13206431e-03],
       [9.46116030e-01, 5.38839697e-02],
       [9.27938394e-01, 7.20616063e-02],
       [6.31359485e-06, 9.99993686e-01],
       [4.73592392e-06, 9.99995264e-01],
       [1.89003026e-01, 8.10996974e-01],
       [2.32516066e-04, 9.99767484e-01],
       [7.49499051e-04, 9.99250501e-01],
       [7.38823136e-01, 2.61176864e-01],
       [5.38886606e-06, 9.99994611e-01],
       [9.64264583e-01, 3.57354167e-02],
       [9.98436215e-01, 1.56378522e-03],
       [9.92180635e-01, 7.81936538e-03]])

In [58]:
y_test, y_preds

(array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0]))

# Randomised Search CV

In [60]:
from sklearn.model_selection import RandomizedSearchCV

In [61]:
model2 = LogisticRegression()

In [62]:
model2

LogisticRegression()

In [64]:
rsv = RandomizedSearchCV(estimator = model2, param_distributions = params, cv = 5, scoring = 'accuracy')

In [65]:
rsv

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1.0, 10.0, 100.0],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [66]:
model3 = rsv.fit(X_train, y_train)

C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
35 f

In [67]:
model3

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1.0, 10.0, 100.0],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [69]:
y_pred2 = model3.predict(X_test)

In [70]:
y_pred2

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [71]:
y_test, y_pred2

(array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0]))

In [72]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test,y_pred2))

print(confusion_matrix(y_test,y_pred2))

print(classification_report(y_test,y_pred2))

1.0
[[12  0]
 [ 0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [73]:
model3.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 10.0}

In [74]:
model3.best_score_

0.9125

# Multiclass Logistic Regression

In [75]:
X, y = make_classification(n_samples=100,
    n_features=10,
    n_informative=4,
    n_classes=3,
    n_clusters_per_class=3,
    )

In [76]:
X.shape

(100, 10)

In [77]:
X

array([[-9.52794922e-01, -1.11583836e+00,  1.07069659e+00,
        -1.62644864e+00, -1.65875637e+00, -4.02145780e-01,
        -2.17740064e-01, -1.01055100e+00, -2.06520447e-01,
        -9.06757542e-02],
       [-3.23672659e-02, -7.48825717e-01,  2.65309733e-02,
         5.04365340e-01, -4.68399257e-01,  1.32825967e-01,
        -8.90155560e-01, -3.79257939e-02,  8.00410360e-01,
        -9.21532053e-01],
       [-2.44658083e-01,  1.41389449e+00, -4.46399968e-01,
        -7.32696691e-01,  1.39383695e+00, -2.08316300e-01,
         1.47411546e+00, -1.95388166e+00,  7.92807010e-01,
         2.43906082e+00],
       [ 1.02811430e+00,  1.48659919e+00, -1.25444304e-01,
        -1.43710370e-01,  1.19383502e+00, -2.15507781e-01,
         1.07215883e+00,  2.65060980e-01, -1.85889795e+00,
        -1.61177586e+00],
       [-6.37255156e-01, -2.90331058e+00,  3.72437698e-01,
         3.84095943e+00, -4.99665997e-01,  1.83737593e+00,
        -2.87128240e+00,  7.00667650e-01, -1.67436429e+00,
         4.

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

In [80]:
X_train.shape

(80, 10)

In [81]:
y_train.shape

(80,)

In [82]:
X_test.shape

(20, 10)

In [85]:
model4 = LogisticRegression(multi_class = 'ovr')

In [86]:
model4

LogisticRegression(multi_class='ovr')

In [89]:
model4 = model4.fit(X_train, y_train)
model4

LogisticRegression(multi_class='ovr')

In [90]:
y_pred3 = model4.predict(X_test)
y_pred3

array([0, 1, 0, 1, 1, 0, 2, 0, 2, 1, 0, 2, 2, 1, 2, 2, 2, 1, 1, 2])

In [91]:
y_test, y_pred3

(array([2, 2, 2, 1, 1, 0, 0, 0, 2, 1, 2, 2, 2, 1, 0, 2, 0, 2, 1, 2]),
 array([0, 1, 0, 1, 1, 0, 2, 0, 2, 1, 0, 2, 2, 1, 2, 2, 2, 1, 1, 2]))

In [92]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test,y_pred3))

print(confusion_matrix(y_test,y_pred3))

print(classification_report(y_test,y_pred3))

0.6
[[2 0 3]
 [0 5 0]
 [3 2 5]]
              precision    recall  f1-score   support

           0       0.40      0.40      0.40         5
           1       0.71      1.00      0.83         5
           2       0.62      0.50      0.56        10

    accuracy                           0.60        20
   macro avg       0.58      0.63      0.60        20
weighted avg       0.59      0.60      0.59        20



In [93]:
gcvs = GridSearchCV(estimator = model4, param_grid=params, cv=5, scoring='accuracy')

In [94]:
gcvs

GridSearchCV(cv=5, estimator=LogisticRegression(multi_class='ovr'),
             param_grid={'C': [1.0, 10.0, 100.0],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [96]:
gcvs.fit(X_train, y_train)

C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saike\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter 

GridSearchCV(cv=5, estimator=LogisticRegression(multi_class='ovr'),
             param_grid={'C': [1.0, 10.0, 100.0],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [97]:
results = gcvs.predict(X_test)

In [99]:
y_test, results

(array([2, 2, 2, 1, 1, 0, 0, 0, 2, 1, 2, 2, 2, 1, 0, 2, 0, 2, 1, 2]),
 array([0, 1, 0, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 1, 2, 2, 2, 1, 1, 2]))

In [100]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test,results))

print(confusion_matrix(y_test,results))

print(classification_report(y_test,results))



0.65
[[3 0 2]
 [0 5 0]
 [3 2 5]]
              precision    recall  f1-score   support

           0       0.50      0.60      0.55         5
           1       0.71      1.00      0.83         5
           2       0.71      0.50      0.59        10

    accuracy                           0.65        20
   macro avg       0.64      0.70      0.66        20
weighted avg       0.66      0.65      0.64        20



In [102]:
gcvs.best_params_

{'C': 1.0, 'penalty': 'l1', 'solver': 'liblinear'}

In [103]:
gcvs.best_score_

0.575