In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=100, n_features = 10, n_classes= 2)

In [3]:
X

array([[ 1.08916463e+00,  8.25405172e-01, -9.44599376e-01,
         1.70187263e+00, -7.48083141e-01,  5.00995393e-01,
         8.49592349e-01,  1.76974609e+00, -2.06906793e+00,
        -6.22180918e-01],
       [ 9.09470525e-01,  2.34763598e+00, -9.50619033e-01,
        -1.05339168e+00,  8.01301832e-01,  9.51198013e-01,
         2.03840979e-01,  9.28228728e-01,  7.88036987e-01,
        -3.82195072e-01],
       [-2.32423447e-01, -3.32199220e+00,  3.78461962e-01,
         9.70623771e-01, -3.48313775e-01, -4.67775097e-01,
         4.86144131e-02, -7.11221414e-01, -3.71991157e-01,
        -9.60212308e-01],
       [ 7.35662861e-01,  4.12497350e-01,  1.60265223e+00,
         4.75788208e-01, -2.38337193e+00, -1.39352443e+00,
        -6.49717561e-01, -1.52368762e-01, -1.27216068e+00,
         3.32569627e-01],
       [ 1.02400110e+00, -1.18532380e+00, -2.68440950e-02,
        -1.52139576e+00,  9.24561212e-01,  2.67914550e-01,
        -3.45390698e-01,  1.34109876e+00,  5.83606440e-01,
         9.

In [4]:
y

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1])

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.25, random_state= 50)

In [7]:
y_preds

array([1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1])

In [18]:
from sklearn.naive_bayes import GaussianNB
gn = GaussianNB()

In [19]:
model = gn.fit(X_train,y_train)


In [20]:
y_pred= model.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.96
