In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [46]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples = 1000, n_classes =2)

In [47]:
X.shape

(1000, 20)

In [48]:
y

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,

In [49]:
X

array([[-5.25267000e-01,  1.32532803e+00, -1.13937489e+00,
        -1.26674636e+00, -5.81531241e-01,  1.93890190e+00,
         6.73862841e-01,  1.62772097e-01,  1.15639012e+00,
        -7.83042384e-01, -1.39905784e+00, -1.45652601e+00,
        -4.00791156e-01,  7.77050769e-02, -7.41294362e-01,
        -1.37595492e+00,  1.94805408e+00, -3.86125106e-01,
         1.65864537e-01, -5.79166994e-01],
       [-6.33093426e-01,  3.82314826e-01, -5.45070252e-01,
         2.30190859e-02, -1.56369154e-01,  3.59975251e-01,
         1.26311183e+00,  5.92188339e-02, -2.35741198e+00,
        -3.58593837e-01, -5.99067069e-01, -2.92100437e-01,
         3.77807272e-01,  1.84536398e-01,  5.21652656e-01,
        -6.15077397e-01,  1.13948778e+00, -4.49771787e-01,
        -7.30721227e-02,  8.51242878e-01],
       [-9.12189239e-01,  2.21804756e+00,  7.49644762e-02,
        -2.02852450e+00, -1.66911113e+00, -2.35765076e+00,
        -2.62627667e-01,  3.21891961e-01,  1.57090575e+00,
         9.13181898e-01,  2.4

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state = 100)

In [51]:
X_train.shape

(750, 20)

In [52]:
y_train.shape

(750,)

In [53]:
X_test.shape

(250, 20)

In [54]:
from sklearn.svm import SVC
svc_model = SVC()

In [55]:
svc_model = svc_model.fit(X_train, y_train)

In [56]:
svc_model

SVC()

In [57]:
y_pred = svc_model.predict(X_test)
y_pred

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1])

In [58]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.92
[[116   7]
 [ 13 114]]
              precision    recall  f1-score   support

           0       0.90      0.94      0.92       123
           1       0.94      0.90      0.92       127

    accuracy                           0.92       250
   macro avg       0.92      0.92      0.92       250
weighted avg       0.92      0.92      0.92       250



# Hyperparameter tuning

In [59]:
from sklearn.model_selection import GridSearchCV

In [60]:
from sklearn.model_selection import GridSearchCV

In [61]:
params = {
    'C' : [1,10,100],
    'gamma' : [0.1,0.01,0.001],
    'kernel' : ['sigmoid']  # can use  poly, rbf, linear, but sigmoid gives high accuracy
}

In [62]:
model = SVC()

In [63]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold()

gscv = GridSearchCV(estimator = model, param_grid = params, cv=5, scoring='accuracy')

In [64]:
gscv_model = gscv.fit(X_train, y_train)
gscv_model

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 100], 'gamma': [0.1, 0.01, 0.001],
                         'kernel': ['sigmoid']},
             scoring='accuracy')

In [65]:
y_pred1 = gscv_model.predict(X_test)
y_pred1

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1])

In [66]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))
print(classification_report(y_test, y_pred1))

0.94
[[116   7]
 [  8 119]]
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       123
           1       0.94      0.94      0.94       127

    accuracy                           0.94       250
   macro avg       0.94      0.94      0.94       250
weighted avg       0.94      0.94      0.94       250



# SVR

In [166]:
import seaborn as sns
df = sns.load_dataset('tips')

In [106]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [167]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [169]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [170]:
df['sex'].value_counts()

Male      157
Female     87
Name: sex, dtype: int64

In [171]:
df['smoker'].value_counts()

No     151
Yes     93
Name: smoker, dtype: int64

In [172]:
df['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [173]:
df['time'].value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

In [174]:
from sklearn.preprocessing import LabelEncoder

l1 = LabelEncoder()
l2 = LabelEncoder()
l3 = LabelEncoder()


df['sex'] = l1.fit_transform(df['sex'])
df['smoker'] = l2.fit_transform(df['smoker'])
df['time'] = l3.fit_transform(df['time'])

In [175]:
df.head()

total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0  Sun     0     2
1       10.34  1.66    1       0  Sun     0     3
2       21.01  3.50    1       0  Sun     0     3
3       23.68  3.31    1       0  Sun     0     2
4       24.59  3.61    0       0  Sun     0     4

In [176]:
X = df[['tip',	'sex',	'smoker',	'day',	'time',	'size']]
y = df['total_bill']

In [177]:
X

tip  sex  smoker   day  time  size
0    1.01    0       0   Sun     0     2
1    1.66    1       0   Sun     0     3
2    3.50    1       0   Sun     0     3
3    3.31    1       0   Sun     0     2
4    3.61    0       0   Sun     0     4
..    ...  ...     ...   ...   ...   ...
239  5.92    1       0   Sat     0     3
240  2.00    0       1   Sat     0     2
241  2.00    1       1   Sat     0     2
242  1.75    1       0   Sat     0     2
243  3.00    0       0  Thur     0     2

[244 rows x 6 columns]

In [178]:
y

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [179]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.2, random_state = 90)

In [180]:
X_train

tip  sex  smoker  day  time  size
225  2.50    0       1  Fri     1     2
52   5.20    0       0  Sun     0     4
60   3.21    1       1  Sat     0     2
175  3.11    1       1  Sun     0     2
116  5.07    1       0  Sun     0     4
..    ...  ...     ...  ...   ...   ...
67   1.00    0       1  Sat     0     1
159  2.00    1       0  Sun     0     4
114  4.00    0       0  Sun     0     3
157  3.75    0       0  Sun     0     4
91   3.50    1       0  Fri     0     2

[195 rows x 6 columns]

In [182]:
X_test.shape

(49, 6)

##### ColumnTransformer: 
It allows you to apply different transformations to different columns of your dataset. It’s especially useful when you have both numeric and categorical features that need different preprocessing steps.



##### transformers: 
A list of tuples specifying what transformations to apply and to which columns.

#### Format: ('name', transformer, column(s))

##### remainder='passthrough': 
##### Keeps all columns that are not explicitly transformed by ColumnTransformer. This means other columns will remain unchanged in the final output.

In [183]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('onehot', OneHotEncoder(drop='first'),[3])], remainder = 'passthrough' )

In [184]:
type(X_train)

pandas.core.frame.DataFrame

In [185]:
X_train = ct.fit_transform(X_train)
X_train

array([[ 0.  ,  0.  ,  0.  ,  2.5 ,  0.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.2 ,  0.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  3.21,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.11,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.07,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  4.  ,  1.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  1.67,  0.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  2.34,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  3.5 ,  0.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  2.5 ,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  2.  ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  5.17,  0.  ,  0.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  3.76,  1.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  5.15,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.

In [186]:
X_test = ct.fit_transform(X_test)
X_test

array([[0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 5.92, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 2.54, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 1.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 2.5 , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.  , 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 1.64, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 4.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 1.5 , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.31, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.5 , 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.  , 0.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 1.63, 0.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 1.17,

In [187]:
X_train

array([[ 0.  ,  0.  ,  0.  ,  2.5 ,  0.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.2 ,  0.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  3.21,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.11,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.07,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  4.  ,  1.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  1.67,  0.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  2.34,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  3.5 ,  0.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  2.5 ,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  2.  ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  5.17,  0.  ,  0.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  3.76,  1.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  5.15,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.

In [188]:
from sklearn.svm import SVR
model_r = SVR(kernel="sigmoid")

In [189]:
svr_model = model_r.fit(X_train,y_train)

In [190]:
test = svr_model.predict(X_test)

In [191]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,test)
ad_r2 = 1 - (1-r2)*((len(X_train)-1)/(len(X_train)-X_train.shape[1]-1))
print(r2)
print(ad_r2)

-0.6578569640844318
-0.729162639959031
